---
title: "Final Project - Module 8"
author: "Rtists"
date: "2022-12-03"
output: html_document
bibliography: BIOL3140.Rtists.finalproj.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

## Introduction
Climate change may be having a detrimental impact on the conservation of the trans-Gulf migrant (TGM) population. TGMs are neotropical passerines that migrate from Central and South America to temperate latitudes during the northern hemisphere spring, flying non-stop over the Gulf of Mexico and arriving on land between Texas and Florida. TGMs make this journey in order to forage and breed in the temperate latitudes. According to @smith2005arrival and @newton2008the, Evolutionary trade-offs are made depending on if the TGM arrives earlier and has an increased chance of finding a mate and breeding multiple times, or later and having an increased food availability. The dates that TGMs arrive at their destination has become of particular interest to researchers because of these consequences on fitness, and the way that climate change is influencing these arrival dates. According to @both2006climate, spring temperatures are rising, and TGM populations may decline if they fail to shift their breeding site arrival dates accordingly.
There is debate over if and how TGMs and other migrants shift their spring arrival in temperate North America in response to local temperature changes. A 2019 study, @horton2019holding, did not find an overall change in the annual number of migrants between 2007 and 2015 or the annual timing of peak migration from 1995 to 2015; however, they did find that the earliest seasonal movements throughout the region occurred a significant 1.6 days per decade earlier. Also, according to @horton2019holding, the study also found phenological changes over time; the most significant being the emergence of larger-bodies and shorter distance migrants. Despite this study, the topic of migration pattern changes in response to climate change is still hotly debated and needs to be researched further. 
In 2002, the Cornell Laboratory of Ornithology and the National Audubon Society launched eBird, the most popular and far-reaching online program through which amateur birders can submit bird observations. This data supplements what is collected through field, banding, and tracking studies, which are often temporally limited due to the small number of trained experts. This data aims to study the effects of changes in climate change linked local environment parameters on migration phenology. The data collected by eBird covers a wide range of taxonomy and geography. Thousands of amateur birders have contributed over 100 million bird observations to eBird, including historical observations that predate the launch of the program.
We downloaded eBird’s species occurrence data from the Global Biodiversity Information Facility with an R package, rgif, that allows us to access the application programming interface. We also used an R package, rnoa, to interact with NOAA’s National Climate Data Center’s application programming interface in order to compile meteorological data. We used this eBird and meteorological data to study the effects of local weather conditions on the arrival times of TGMs in Massachusetts. We were investigating if local weather conditions that are related to climate change are impacting TGM arrival times, which has implications for fitness changes and species conservation.

## Methods
The first step in completing our project was to select five different trans-Gulf migrant (TGM) bird species. These species should be from different families. We selected: 1, 2, 3, 4, and 5. Data would be sourced from human observations of these species in Massachusetts in the eBird database. Then, using a for loop that passes our species through occ_data(), we retrieved the data from the database. This information would allow us to find the Julian day for each species and see the effect of temperature and wind along the migration route to Massachusetts. Next three sample locations along the migration route are chosen: Mobile, AL, Charlotte, NC, and Boston, MA. Mobile, AL is on the Gulf, Charlotte, NC is roughly in the middle, and Boston, MA is the endpoint. Weather data from each of these locations was downloaded using a token from the NOAA website. Next the eBird data is plotted the proportion of the population that arrived and the predicted arrival time for each. Then another plot is created to illustrate how the Julian day changes over the years. This is then used to see the impact of climate on the arrival date. Weather data was then used to calculate wind direction and results were joined with the species data. The frollmean() function is then used to calculate the mean of the weather variables 5 and 10 days before the arrival day. Lastly, a Linear Mixed-effect Model was created using lme for both weather data sets (single-day and two-week average). An Anova test was run to find the best fit model, and model testing was done using the function dredge().

## Results

## Discussion 

## Author Contributions 
Michael Britt - Bibliography, Discussion
Phoebe Chandler - Methods 
Ellie Falanga - 
Erin Kiley - Introduction
## References 

